repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.11
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --config, pyproject.toml ]
    # Run the formatter.
    - id: ruff-format
      args: [--config, pyproject.toml, --check ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.1
  hooks:
  - id: mypy
    name: mypy
    description: ''
    entry: mypy
    language: python
    'types_or': [python, pyi]
    args: ["--config-file=pyproject.toml"]
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'

- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
  - id: nbstripout